version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - stack.env
    container_name: fleetlink-pro-app
    restart: unless-stopped
